//! macOS backend: screenshots via xcap (CGWindowListCreateImage) /
//! ScreenCaptureKit; mouse events posted natively as CGEvents; keyboard and
//! wheel go through enigo; the accessibility tree comes from
//! ApplicationServices AXUIElement.
//!
//! Coordinate conventions (the macOS concretization of the types.rs contract):
//! - The input coordinate space = CGEvent global **points** (top-left origin,
//!   negative on multi-monitor layouts).
//! - `Capture.origin_x/y` uses the monitor origins reported by xcap directly
//!   (on macOS CGDisplayBounds returns points); `Capture.input_scale_x/y` is
//!   derived backwards from the returned image (points / actual pixel width,
//!   Retina 2x → 0.5) and never trusts the scale_factor estimate; screenshots
//!   are physical pixels.
//! - `cursor_position` returns global input-space coordinates (CGEvent
//!   points), the same space the action coordinates use.
//! - Element positions/sizes returned by AX are also screen point
//!   coordinates, consistent with the input coordinate space.
//!
//! Screenshot implementation: on macOS 15.2+ ScreenCaptureKit is used
//! ([`super::screen_capture_kit`], `SCScreenshotManager::captureImageInRect`
//! — that class method is only available from 15.2); below 15.2 (including
//! 15.0/15.1, which sit in the periodic "keep allowing screen recording"
//! window) we fall back to xcap's CGWindowListCreateImage path (that API is
//! obsoleted in
//! the macOS 15 SDK and on Sequoia+ triggers the periodic "keep allowing
//! screen recording" system confirmation, but on older systems it remains the
//! only option). The app supports macOS 11 at minimum:
//! ScreenCaptureKit.framework is weakly linked (see build.rs); systems before
//! 12.3 are skipped by dyld and take the fallback.
//!
//! Permissions (TCC, two independent grants; after granting, both usually
//! need an app restart to take effect):
//! - Screen Recording: CGPreflightScreenCaptureAccess is preflighted before
//!   capture; when missing, an explicit `screen_recording_denied` error is
//!   returned; the tool path does **not** proactively trigger the system
//!   dialog.
//! - Accessibility: AXIsProcessTrusted is preflighted before input injection
//!   and AX tree access; when missing, an explicit `accessibility_denied`
//!   error is returned — unauthorized CGEventPost is **silently dropped** by
//!   WindowServer (no error return); without the preflight you get "the click
//!   succeeded but nothing happened".
//! Grant onboarding is provided by [`request_permissions`] for the
//! integration layer to call from the settings page / onboarding flow.
//!
//! Threading contract: AXUIElement is a CFType (!Send/!Sync). This backend
//! holds no AX objects across calls — every AXUIElement/AXValue is created,
//! used, and released within a single method call on the backend worker
//! thread (backend.rs guarantees worker-thread affinity; objects never leave
//! the thread), so the struct relies on auto Send alone (Enigo already has an
//! internal unsafe impl Send); no hand-written unsafe impl is needed.
//!
//! Autorelease-pool invariant: the backend worker thread has no Obj-C
//! runloop and no autorelease pool. Every ObjC/CF call on the input/capture
//! paths below (and in [`super::screen_capture_kit`]) must therefore return
//! +1/CF-typed objects or plain primitives — no autoreleased returns. This
//! holds today, but one innocent future edit returning an autoreleased object
//! would start leaking silently; if that ever changes, wrap the call site in
//! `objc2::rc::autoreleasepool`.
//!
//! CF layer notes: the AX attribute-name constants (kAXRoleAttribute etc.)
//! are not generated by objc2-application-services 0.3.2's header-translator,
//! and CFDictionary/CFArray's generic default parameters are crate-private
//! types that cannot be constructed externally — hence attribute names use
//! NSString (toll-free bridged to CFString) and a small set of
//! CoreFoundation extern "C" functions for array/dictionary/boolean
//! (CFRelease itself is shared via `platform::cursor`, the same FFI-sharing
//! precedent as detach.rs). Objects returned by the AX "Copy
//! rule" are always converted into typed smart pointers
//! (`CFRetained<AXUIElement>` / `CFRetained<AXValue>` / `Retained<NSString>`)
//! after a GetTypeID precheck; this module never dereferences raw pointers
//! (the definitive fix for CodeQL invalid-pointer-dereference: the bare
//! `&*(ptr as *const T)` bridging casts have all been removed).

use std::ffi::c_void;
use std::fmt::Write as _;
use std::ptr::NonNull;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread::sleep;
use std::time::{Duration, Instant};

use enigo::{Direction, Enigo, Keyboard, Mouse, Settings};
use objc2::rc::Retained;
use objc2_application_services::{AXError, AXIsProcessTrusted, AXUIElement, AXValue, AXValueType};
use objc2_core_foundation::{
    CFRetained, kCFTypeDictionaryKeyCallBacks, kCFTypeDictionaryValueCallBacks,
};
use objc2_core_graphics::{CGPreflightScreenCaptureAccess, CGRequestScreenCaptureAccess};
use objc2_foundation::{NSPoint, NSSize, NSString};
use xcap::Monitor;

use super::super::backend::ComputerUseBackend;
use super::super::types::{
    Capabilities, Capture, ComputerUseError, ElementInfo, Key, MouseButton, ScrollDirection,
    UiTreeOptions,
};
use super::helpers::{
    TYPE_CHUNK_CHARS, TypeRun, drag_waypoints, map_scroll, normalize_typed_newlines, sanitize_name,
    screening_name, split_type_runs,
};
use crate::platform::cursor::{CFRelease, CursorPositionError, cursor_position};

/// Wait before a click so the preceding move settles (the target process
/// consumes the mouse-moved event).
const CLICK_SETTLE_MS: u64 = 30;
/// Gap between consecutive clicks in a double/triple click (far below the
/// system double-click threshold; enigo maintains clickState internally per
/// NSEvent.doubleClickInterval, and double/triple clicks are recognized from
/// it).
const MULTI_CLICK_INTERVAL_MS: u64 = 40;
/// Pause after the drag press and before movement starts, giving the target
/// window time to enter drag-recognition state.
const DRAG_PRESS_SETTLE_MS: u64 = 60;
/// Number of interpolated drag path steps (some apps only recognize a drag
/// after receiving enough motion events).
const DRAG_STEPS: usize = 8;
/// Delay between adjacent drag waypoints.
const DRAG_STEP_DELAY_MS: u64 = 12;
/// Pause between pressing all keys and releasing them in reverse; improves
/// the hit rate of modifier chords (cmd+Tab etc.).
const CHORD_HOLD_MS: u64 = 20;
/// Granularity of the hold_key sleep: a stop/timeout cancel flag is polled
/// at least this often, so an abandoned hold stops within this window
/// instead of the full hold duration.
const HOLD_CANCEL_POLL_MS: u64 = 100;

/// `ui_tree` defaults/caps: depth and node count (keeps giant trees from
/// overwhelming the worker thread and the text budget).
const DEFAULT_TREE_MAX_DEPTH: u32 = 8;
const DEFAULT_TREE_MAX_NODES: u32 = 400;
const MAX_TREE_DEPTH: u32 = 24;
const MAX_TREE_NODES: u32 = 2000;
/// Character cap for a single-line name.
const MAX_NODE_NAME_CHARS: usize = 80;
/// Global message timeout (seconds) for AX's synchronous cross-process IPC.
/// The default is about 6s; heavy apps (browsers/Electron) can hang on
/// attribute reads, so it is tightened to 2s to protect the worker thread.
const AX_MESSAGING_TIMEOUT_SECS: f32 = 2.0;
/// Overall traversal time limit for `ui_tree`. A single AX call is bounded by
/// [`AX_MESSAGING_TIMEOUT_SECS`], but the worst-case total for a whole tree
/// (default 400 nodes × up to 7 attribute reads per node) has no upper bound
/// (it can pin the worker thread for about 1.5 hours); when the limit hits,
/// traversal aborts and sets truncated — the partially generated tree remains
/// valid.
const AX_TREE_TIME_LIMIT: Duration = Duration::from_secs(10);
/// Abort threshold for consecutive `AXError::CannotComplete` (the target
/// process is unresponsive/hung). This error should not occur consecutively
/// in a healthy tree; consecutive occurrences mean the target is hung, and
/// continuing would just burn 2s per attribute.
const AX_CANNOT_COMPLETE_LIMIT: u32 = 3;
/// Tolerance (points) for the click landing guard: when the actual cursor
/// position deviates from the most recent synthetic move target by more than
/// this, click/press re-moves to the target first.
const CLICK_POSITION_TOLERANCE_PT: i32 = 2;

/// Explicit error when Screen Recording is denied (the grant needs an app
/// restart to take effect; the error says so).
const SCREEN_RECORDING_DENIED: &str = "screen_recording_denied: enable in System Settings → Privacy & Security → Screen Recording, then restart the app";
/// Explicit error when Accessibility is denied.
const ACCESSIBILITY_DENIED: &str = "accessibility_denied: enable in System Settings → Privacy & Security → Accessibility, then restart the app";

#[link(name = "CoreGraphics", kind = "framework")]
unsafe extern "C" {
    /// CGEventRef CGEventCreateMouseEvent(CGEventSourceRef, CGEventType,
    /// CGPoint, CGMouseButton). Types declared manually per the SDK prototype:
    /// the enums are u32.
    fn CGEventCreateMouseEvent(
        source: *const c_void,
        mouse_type: u32,
        at: NSPoint,
        button: u32,
    ) -> *const c_void;
    /// void CGEventSetIntegerValueField(CGEventRef, CGEventField, int64_t).
    fn CGEventSetIntegerValueField(event: *const c_void, field: u32, value: i64);
    /// void CGEventPost(CGEventTapLocation, CGEventRef).
    fn CGEventPost(tap: u32, event: *const c_void);
}

#[link(name = "CoreFoundation", kind = "framework")]
unsafe extern "C" {
    fn CFGetTypeID(cf: *const c_void) -> usize;
    fn CFStringGetTypeID() -> usize;
    fn CFBooleanGetTypeID() -> usize;
    /// The C prototype returns `Boolean` (unsigned char); declared as u8 per
    /// the per-type consistency rule and checked with `!= 0` (Rust `bool`'s
    /// ABI happens to be compatible in practice, but we do not rely on it).
    fn CFBooleanGetValue(boolean: *const c_void) -> u8;
    fn CFArrayGetTypeID() -> usize;
    fn CFArrayGetCount(array: *const c_void) -> isize;
    fn CFArrayGetValueAtIndex(array: *const c_void, index: isize) -> *const c_void;
    static kCFBooleanTrue: *const c_void;
    fn CFDictionaryCreate(
        allocator: *const c_void,
        keys: *const *const c_void,
        values: *const *const c_void,
        num_values: isize,
        key_callbacks: *const c_void,
        value_callbacks: *const c_void,
    ) -> *const c_void;
}

#[link(name = "ApplicationServices", kind = "framework")]
unsafe extern "C" {
    /// Accessibility query with options (kAXTrustedCheckOptionPrompt can
    /// trigger the system grant dialog). The signature is declared manually
    /// as *const c_void: the crate's version takes Option<&CFDictionary>, and
    /// CFDictionary's generic default parameters are crate-private types, so
    /// the reference cannot be constructed externally. The C prototype
    /// returns `Boolean` (unsigned char) → u8.
    fn AXIsProcessTrustedWithOptions(options: *const c_void) -> u8;
    /// objc2-application-services only exposes type_id through a crate-private
    /// ConcreteType trait; the C symbols are declared directly here for AX
    /// object type checks.
    fn AXUIElementGetTypeID() -> usize;
    fn AXValueGetTypeID() -> usize;
}

fn map_xcap_err(context: &str, err: xcap::XCapError) -> ComputerUseError {
    ComputerUseError::failed(format!("{context}: {err}"))
}

fn map_input_err(context: &str, err: enigo::InputError) -> ComputerUseError {
    ComputerUseError::failed(format!("{context}: {err}"))
}

fn screen_recording_granted() -> bool {
    CGPreflightScreenCaptureAccess()
}

fn accessibility_granted() -> bool {
    // SAFETY: no arguments, purely queries this process's TCC grant state,
    // shows no dialog, callable on any thread.
    unsafe { AXIsProcessTrusted() }
}

fn screen_recording_error() -> ComputerUseError {
    ComputerUseError::unavailable(SCREEN_RECORDING_DENIED)
}

fn accessibility_error() -> ComputerUseError {
    ComputerUseError::unavailable(ACCESSIBILITY_DENIED)
}

/// A single-level attribute read along the focus chain (focused_element)
/// failed (fail-closed).
fn focused_chain_error(attribute: &str, err: AXError) -> ComputerUseError {
    ComputerUseError::failed(format!("reading {attribute} failed: AXError({})", err.0))
}

/// Triggers the system dialogs for both TCC grants (Screen Recording +
/// Accessibility). Called by the `computer_use_request_permissions` Tauri
/// command via `platform::request_permissions`; the **tool path must not call
/// it** (tools only return explicit errors).
/// Each dialog appears at most once per session; after granting, an app
/// restart is usually required for it to take effect.
pub fn request_permissions() {
    // The return value is the grant state at call time; it is ignored here —
    // the call is only made to trigger the dialog.
    let _ = CGRequestScreenCaptureAccess();
    // AXIsProcessTrustedWithOptions({kAXTrustedCheckOptionPrompt: true}).
    // The string value of kAXTrustedCheckOptionPrompt is always
    // "AXTrustedCheckOptionPrompt"; a toll-free bridged NSString is used as
    // the key, working around the crate not generating that static.
    let key = NSString::from_str("AXTrustedCheckOptionPrompt");
    let keys = [Retained::as_ptr(&key).cast::<c_void>()];
    // SAFETY: kCFBooleanTrue is a valid CFBoolean singleton exported by
    // CoreFoundation, valid for the lifetime of the process; only its address
    // is lent to the temporary dictionary here.
    let values = [unsafe { kCFBooleanTrue }];
    // The kCFType callbacks are the crux of correctness (review finding: with
    // NULL callbacks the key is compared by pointer identity, so HIServices'
    // value lookup against its own global kAXTrustedCheckOptionPrompt
    // instance never matches — the Accessibility system dialog silently never
    // triggers and the user stays stuck at accessibility_denied).
    // kCFTypeDictionary*CallBacks compare by content via CFEqual
    // (CFString/NSString value equality) and retain the key/value; enigo and
    // the rest of the ecosystem follow the same rule. SAFETY: both statics
    // are exported by CoreFoundation and valid for the process lifetime; only
    // their addresses are borrowed.
    let key_callbacks = unsafe { &kCFTypeDictionaryKeyCallBacks };
    // SAFETY: same CoreFoundation-exported static as the key callbacks —
    // valid for the process lifetime; only its address is borrowed.
    let value_callbacks = unsafe { &kCFTypeDictionaryValueCallBacks };
    // SAFETY: keys/values point at equal-length (1) arrays on this function's
    // stack; the kCFType callbacks retain the key/value at creation, after
    // which the dictionary no longer depends on their lifetime; the returned
    // +1 dictionary is CFReleased within this function.
    let options = unsafe {
        CFDictionaryCreate(
            std::ptr::null(),
            keys.as_ptr(),
            values.as_ptr(),
            1,
            std::ptr::from_ref(key_callbacks).cast::<c_void>(),
            std::ptr::from_ref(value_callbacks).cast::<c_void>(),
        )
    };
    if options.is_null() {
        return;
    }
    // SAFETY: options is the valid CFDictionaryRef successfully created
    // above; AXIsProcessTrustedWithOptions only reads it and shows the dialog
    // asynchronously; CFRelease releases it exactly once.
    unsafe {
        let _ = AXIsProcessTrustedWithOptions(options) != 0;
        CFRelease(options);
    }
}

/// Reads the cursor position in CGEvent global point coordinates (top-left
/// origin). Grant-free (only event synthesis requires Accessibility),
/// callable on any thread — the extern declarations and the read itself are
/// shared with detach.rs via [`crate::platform::cursor`].
fn cursor_points() -> Result<(i32, i32), ComputerUseError> {
    cursor_position().map_err(|err| {
        let message = match err {
            CursorPositionError::NullEvent => {
                "CGEventCreate returned null while reading the cursor position"
            }
            CursorPositionError::NonFinite => "CGEventGetLocation returned non-finite coordinates",
        };
        ComputerUseError::failed(message)
    })
}

/// Monitor to capture: the one holding the cursor (on macOS from_point takes
/// point coordinates); falls back to the primary monitor, then to the first
/// monitor.
fn pick_monitor(cursor: Option<(i32, i32)>) -> Result<Monitor, ComputerUseError> {
    if let Some((x, y)) = cursor {
        if let Ok(monitor) = Monitor::from_point(x, y) {
            return Ok(monitor);
        }
    }
    let mut monitors =
        Monitor::all().map_err(|err| map_xcap_err("cannot enumerate monitors", err))?;
    if let Some(primary) = monitors
        .iter()
        .position(|m| m.is_primary().unwrap_or(false))
    {
        return Ok(monitors.swap_remove(primary));
    }
    monitors
        .drain(..)
        .next()
        .ok_or_else(|| ComputerUseError::unavailable("no monitor available for screen capture"))
}

/// This crate's `Key` → enigo key. macOS differences:
/// - `Char` goes through `Unicode`: enigo on macOS reverse-maps the keycode
///   via the current keyboard layout. When the reverse lookup misses (a
///   character outside the layout), enigo returns the initial keycode 0 —
///   i.e. ANSI 'a' — **silently injecting the wrong key** instead of erroring.
///   Characters outside the safe set ([`is_layout_safe_char`]) therefore fail
///   explicitly here (fail-closed); arbitrary text should go through
///   `type_text` instead (direct Unicode injection, bypassing the layout
///   reverse lookup).
/// - `Insert`: enigo's `Key::Insert` variant is cfg-excluded on macOS (it
///   does not exist); it maps to `Help` — the ANSI HELP keycode (0x72) is the
///   key at the Insert position on extended Mac keyboards, and RDP/VNC/VM
///   scenarios pass it through as Insert by this convention.
fn map_key(key: Key) -> Result<enigo::Key, ComputerUseError> {
    use enigo::Key as EK;
    let mapped = match key {
        Key::Control => EK::Control,
        Key::Alt => EK::Alt,
        Key::Shift => EK::Shift,
        Key::Meta => EK::Meta,
        Key::Enter => EK::Return,
        Key::Escape => EK::Escape,
        Key::Tab => EK::Tab,
        Key::Space => EK::Space,
        Key::Backspace => EK::Backspace,
        Key::Delete => EK::Delete,
        Key::Insert => EK::Help,
        Key::Up => EK::UpArrow,
        Key::Down => EK::DownArrow,
        Key::Left => EK::LeftArrow,
        Key::Right => EK::RightArrow,
        Key::Home => EK::Home,
        Key::End => EK::End,
        Key::PageUp => EK::PageUp,
        Key::PageDown => EK::PageDown,
        Key::Function(n) => match n {
            1 => EK::F1,
            2 => EK::F2,
            3 => EK::F3,
            4 => EK::F4,
            5 => EK::F5,
            6 => EK::F6,
            7 => EK::F7,
            8 => EK::F8,
            9 => EK::F9,
            10 => EK::F10,
            11 => EK::F11,
            12 => EK::F12,
            other => {
                return Err(ComputerUseError::failed(format!(
                    "function key f{other} is outside the supported f1..=f12 range"
                )));
            }
        },
        Key::Char(c) => {
            if !is_layout_safe_char(c) {
                // enigo returns keycode 0 (= ANSI 'a') for out-of-layout
                // characters and only the base keycode for Shift-state
                // characters — both silently inject the wrong key, so this
                // must fail explicitly here rather than being handed to
                // enigo.
                // No echo of the offending character: this string lands in
                // the audit log's error field verbatim.
                return Err(ComputerUseError::failed(
                    "a character is not representable in the current keyboard layout; \
                     use the type action for arbitrary text",
                ));
            }
            EK::Unicode(c)
        }
    };
    Ok(mapped)
}

/// The safe character set that enigo on macOS can reverse-map from
/// `Key::Unicode(c)` and inject **verbatim**: US-layout characters typeable
/// without Shift (lowercase letters, digits, space, and unshifted
/// punctuation). Anything outside the set is rejected, for two reasons (see
/// enigo's `get_layoutdependent_keycode` and `add_event_flag`
/// implementations):
/// 1. Out-of-layout characters (CJK, emoji, control characters, etc.) miss
///    the reverse lookup; enigo returns the initial keycode 0 = ANSI 'a',
///    silently injecting 'a';
/// 2. Shift-state characters (uppercase letters, combined punctuation like
///    `+`/`!`) may hit the reverse lookup, but enigo takes only the base
///    keycode without the Shift event flag, injecting the unshifted wrong
///    character.
fn is_layout_safe_char(c: char) -> bool {
    c.is_ascii_lowercase()
        || c.is_ascii_digit()
        || c == ' '
        || matches!(
            c,
            '`' | '-' | '=' | '[' | ']' | '\\' | ';' | '\'' | ',' | '.' | '/'
        )
}

/// Mouse event types from CGEventType (raw values of the `CGEventType`
/// enum).
const CG_EVENT_LEFT_MOUSE_DOWN: u32 = 1;
const CG_EVENT_LEFT_MOUSE_UP: u32 = 2;
const CG_EVENT_RIGHT_MOUSE_DOWN: u32 = 3;
const CG_EVENT_RIGHT_MOUSE_UP: u32 = 4;
const CG_EVENT_MOUSE_MOVED: u32 = 5;
const CG_EVENT_LEFT_MOUSE_DRAGGED: u32 = 6;
const CG_EVENT_RIGHT_MOUSE_DRAGGED: u32 = 7;
// Middle button = kCGEventOtherMouseDown/Up/Dragged = 25/26/27 (CGEventType
// enum in vendored core-graphics 0.25, src/event.rs:200-224; 21 is undefined
// and 22 is kCGEventScrollWheel, so the old 21/22/25 values silently no-op'ed
// middle clicks and posted a junk scroll event for middle mouse_up).
const CG_EVENT_OTHER_MOUSE_DOWN: u32 = 25;
const CG_EVENT_OTHER_MOUSE_UP: u32 = 26;
const CG_EVENT_OTHER_MOUSE_DRAGGED: u32 = 27;
/// Raw values of the CGMouseButton enum.
const CG_MOUSE_BUTTON_LEFT: u32 = 0;
const CG_MOUSE_BUTTON_RIGHT: u32 = 1;
const CG_MOUSE_BUTTON_CENTER: u32 = 2;
/// kCGHIDEventTap: the tap location for event injection (consistent with
/// enigo's CGEventTapLocation::HID).
const CG_EVENT_TAP_HID: u32 = 0;
/// kCGMouseEventClickState: the click-count event field (the basis for
/// double/triple-click recognition).
const CG_EVENT_FIELD_CLICK_STATE: u32 = 1;

fn cg_mouse_button(button: MouseButton) -> u32 {
    match button {
        MouseButton::Left => CG_MOUSE_BUTTON_LEFT,
        MouseButton::Right => CG_MOUSE_BUTTON_RIGHT,
        MouseButton::Middle => CG_MOUSE_BUTTON_CENTER,
    }
}

/// The (down, up, dragged) CGEventType values for this mouse button.
fn cg_mouse_event_types(button: MouseButton) -> (u32, u32, u32) {
    match button {
        MouseButton::Left => (
            CG_EVENT_LEFT_MOUSE_DOWN,
            CG_EVENT_LEFT_MOUSE_UP,
            CG_EVENT_LEFT_MOUSE_DRAGGED,
        ),
        MouseButton::Right => (
            CG_EVENT_RIGHT_MOUSE_DOWN,
            CG_EVENT_RIGHT_MOUSE_UP,
            CG_EVENT_RIGHT_MOUSE_DRAGGED,
        ),
        MouseButton::Middle => (
            CG_EVENT_OTHER_MOUSE_DOWN,
            CG_EVENT_OTHER_MOUSE_UP,
            CG_EVENT_OTHER_MOUSE_DRAGGED,
        ),
    }
}

/// The CG event type (and accompanying mouse button) a synthetic move must
/// use given the buttons this backend itself holds pressed: apps recognize a
/// drag only via the Dragged event types (review finding: MouseMoved while a
/// button was held turned a down → move → up sequence into a plain click).
/// Without a held button it stays the plain MouseMoved.
fn move_event_type(held: &[MouseButton]) -> (u32, u32) {
    if held.contains(&MouseButton::Left) {
        (CG_EVENT_LEFT_MOUSE_DRAGGED, CG_MOUSE_BUTTON_LEFT)
    } else if held.contains(&MouseButton::Right) {
        (
            CG_EVENT_RIGHT_MOUSE_DRAGGED,
            cg_mouse_button(MouseButton::Right),
        )
    } else if held.contains(&MouseButton::Middle) {
        (
            CG_EVENT_OTHER_MOUSE_DRAGGED,
            cg_mouse_button(MouseButton::Middle),
        )
    } else {
        (CG_EVENT_MOUSE_MOVED, CG_MOUSE_BUTTON_LEFT)
    }
}

/// Press modifiers before character/named keys (stable order otherwise):
/// enigo's macOS backend attaches its accumulated modifier flags only to the
/// keys pressed after the modifier (review finding: `s+ctrl` used to inject a
/// bare `s` followed by a lone ctrl press).
fn ordered_chord_keys(keys: &[Key]) -> Vec<Key> {
    let mut ordered = keys.to_vec();
    ordered.sort_by_key(|key| !matches!(key, Key::Control | Key::Alt | Key::Shift | Key::Meta));
    ordered
}

/// Password field detection: the authoritative signal is subrole
/// AXSecureTextField (exposed by AppKit/Safari/Chrome); a few apps report
/// secure fields directly as role AXSecureTextField.
fn is_secure_text(role: &str, subrole: &str) -> bool {
    subrole == "AXSecureTextField" || role == "AXSecureTextField"
}

/// Releases pressed keys in reverse; even on a mid-way error, best-effort
/// releases all of them and returns the first error.
fn release_reverse(pressed: &[enigo::Key], enigo: &mut Enigo) -> Result<(), enigo::InputError> {
    let mut first_err = None;
    for key in pressed.iter().rev() {
        if let Err(err) = enigo.key(*key, Direction::Release) {
            if first_err.is_none() {
                first_err = Some(err);
            }
        }
    }
    match first_err {
        Some(err) => Err(err),
        None => Ok(()),
    }
}

// ---------------------------------------------------------------------------
// Accessibility (AX) layer
// ---------------------------------------------------------------------------

/// RAII release for the +1 CF objects returned by the AX "Copy rule" (checked
/// non-null at construction). After a type precheck via
/// [`CfObject::type_id`], the `into_*` methods convert it into objc2/CF typed
/// smart pointers — this module keeps no raw-pointer dereferences at all (the
/// definitive fix for CodeQL invalid-pointer-dereference, which also
/// concentrates type checking in a single place).
struct CfObject(NonNull<c_void>);

impl CfObject {
    /// The underlying pointer (for read-only extern calls on
    /// CFArray/CFBoolean; never dereferenced).
    fn inner(&self) -> NonNull<c_void> {
        self.0
    }

    fn type_id(&self) -> usize {
        // SAFETY: self.0 is non-null and points at a live CF object (this
        // guard holds the +1); CFGetTypeID is a pure type query.
        unsafe { CFGetTypeID(self.0.as_ptr()) }
    }

    /// Converts to a +1 `Retained<NSString>` (toll-free bridged) after
    /// verifying the type is CFString. Returns None on a type mismatch (the
    /// guard still releases via Drop).
    fn into_ns_string(self) -> Option<Retained<NSString>> {
        // SAFETY: CFStringGetTypeID is a pure type query.
        if self.type_id() != unsafe { CFStringGetTypeID() } {
            return None;
        }
        // SAFETY: self.0 points at a live CFString (this guard holds the +1;
        // ownership moves into Retained via from_raw); CFString and NSString
        // are toll-free bridged — the same Obj-C object — and Retained's
        // objc_release on drop is equivalent to CFRelease.
        // NonNull::cast preserves *mut: Retained::from_raw only accepts *mut.
        let text = unsafe { Retained::from_raw(self.0.cast::<NSString>().as_ptr()) };
        // The +1 has been handed to Retained: suppress CfObject::drop to
        // avoid a double release.
        std::mem::forget(self);
        text
    }

    /// Converts to a +1 `CFRetained<AXUIElement>` after verifying the type.
    /// Returns None on a type mismatch (the guard still releases via Drop).
    fn into_ui_element(self) -> Option<CFRetained<AXUIElement>> {
        // SAFETY: AXUIElementGetTypeID is a pure type query.
        if self.type_id() != unsafe { AXUIElementGetTypeID() } {
            return None;
        }
        // SAFETY: verified as AXUIElement; the +1 ownership moves into
        // CFRetained via from_raw (CFRelease on drop, equivalent to the
        // previous manual release).
        let element = unsafe { CFRetained::from_raw(self.0.cast::<AXUIElement>()) };
        // The +1 has been handed to CFRetained: suppress CfObject::drop to
        // avoid a double release.
        std::mem::forget(self);
        Some(element)
    }

    /// Converts to a +1 `CFRetained<AXValue>` after verifying the type.
    /// Returns None on a type mismatch (the guard still releases via Drop).
    fn into_ax_value(self) -> Option<CFRetained<AXValue>> {
        // SAFETY: AXValueGetTypeID is a pure type query.
        if self.type_id() != unsafe { AXValueGetTypeID() } {
            return None;
        }
        // SAFETY: verified as AXValue; the +1 ownership moves into CFRetained
        // via from_raw.
        let value = unsafe { CFRetained::from_raw(self.0.cast::<AXValue>()) };
        // The +1 has been handed to CFRetained: suppress CfObject::drop to
        // avoid a double release.
        std::mem::forget(self);
        Some(value)
    }
}

impl Drop for CfObject {
    fn drop(&mut self) {
        // SAFETY: self.0 is the +1 object returned by the AX Copy rule
        // (checked non-null at construction); when ownership was not handed
        // over via into_*, it is released exactly once here and not used
        // afterwards.
        unsafe { CFRelease(self.0.as_ptr()) };
    }
}

/// AX attribute-name set. The kAX*Attribute string constants are not
/// generated by objc2-application-services 0.3.2, so NSString literals are
/// used (the values are stable and documented; toll-free bridged to CFString,
/// directly usable with the AX APIs). Constructed once per
/// ui_tree/element_at_point/focused_element call and reused by all nodes in
/// the traversal.
struct AxNames {
    role: Retained<NSString>,
    title: Retained<NSString>,
    /// description: the accessible name of web content in browsers/Electron
    /// usually lives only on AXDescription (AXTitle is empty); T3 denylist
    /// matching depends on it (review defect T3-Web).
    description: Retained<NSString>,
    subrole: Retained<NSString>,
    position: Retained<NSString>,
    size: Retained<NSString>,
    enabled: Retained<NSString>,
    focused: Retained<NSString>,
    children: Retained<NSString>,
    focused_application: Retained<NSString>,
    focused_window: Retained<NSString>,
    focused_ui_element: Retained<NSString>,
}

impl AxNames {
    fn new() -> Self {
        Self {
            role: NSString::from_str("AXRole"),
            title: NSString::from_str("AXTitle"),
            description: NSString::from_str("AXDescription"),
            subrole: NSString::from_str("AXSubrole"),
            position: NSString::from_str("AXPosition"),
            size: NSString::from_str("AXSize"),
            enabled: NSString::from_str("AXEnabled"),
            focused: NSString::from_str("AXFocused"),
            children: NSString::from_str("AXChildren"),
            focused_application: NSString::from_str("AXFocusedApplication"),
            focused_window: NSString::from_str("AXFocusedWindow"),
            focused_ui_element: NSString::from_str("AXFocusedUIElement"),
        }
    }
}

/// Reads a single AX attribute (Copy rule, +1). Returns:
/// - `Ok(Some)`: the attribute has a value; the +1 object is released under
///   [`CfObject`] management;
/// - `Ok(None)`: the call succeeded but the attribute has no value (NoValue)
///   or returned an empty object;
/// - `Err`: the AX call failed — `AttributeUnsupported` (attribute
///   unsupported), `CannotComplete` (target process unresponsive/hung), etc.
///   Tree traversal books these errors and aborts on them (see
///   [`AttrErrors`]); the single-element path fails closed on them.
fn copy_attr(element: &AXUIElement, attribute: &NSString) -> Result<Option<CfObject>, AXError> {
    let mut raw = std::ptr::null();
    let Some(out) = NonNull::new(&mut raw) else {
        return Ok(None); // the address of a &mut local is never null; this only avoids unwrap
    };
    // SAFETY: `out` points at a valid out pointer on this function's stack
    // (NonNull<*const CFType>); attribute is an NSString, toll-free bridged
    // to CFString; the output value is used only when Success is returned and
    // the output is non-null.
    let err = unsafe { element.copy_attribute_value(attribute.as_ref(), out) };
    match err {
        // Success with a null output pointer: treated as no value.
        AXError::Success => Ok(NonNull::new(raw.cast_mut()).map(|ptr| CfObject(ptr.cast()))),
        other => Err(other),
    }
}

fn ax_string(element: &AXUIElement, attribute: &NSString) -> Result<Option<String>, AXError> {
    let Some(obj) = copy_attr(element, attribute)? else {
        return Ok(None);
    };
    // A type mismatch (not a CFString) is treated as missing: the tree
    // traversal does not hard-fail, and the single-element path is
    // backstopped by ensure_readable's all-empty check.
    Ok(obj.into_ns_string().map(|text| text.to_string()))
}

fn ax_bool(element: &AXUIElement, attribute: &NSString) -> Result<Option<bool>, AXError> {
    let Some(obj) = copy_attr(element, attribute)? else {
        return Ok(None);
    };
    // SAFETY: CFBooleanGetTypeID is a pure type query.
    if obj.type_id() != unsafe { CFBooleanGetTypeID() } {
        return Ok(None);
    }
    // SAFETY: verified as CFBoolean; pure read, the pointer is only passed as
    // an argument, never dereferenced.
    Ok(Some(
        unsafe { CFBooleanGetValue(obj.inner().as_ptr()) } != 0,
    ))
}

/// Reads an AXUIElement-typed attribute (Copy rule +1, managed by CFRetained).
fn ax_ui_element(
    element: &AXUIElement,
    attribute: &NSString,
) -> Result<Option<CFRetained<AXUIElement>>, AXError> {
    let Some(obj) = copy_attr(element, attribute)? else {
        return Ok(None);
    };
    Ok(obj.into_ui_element())
}

fn ax_point(element: &AXUIElement, attribute: &NSString) -> Result<Option<NSPoint>, AXError> {
    let Some(obj) = copy_attr(element, attribute)? else {
        return Ok(None);
    };
    let Some(value) = obj.into_ax_value() else {
        return Ok(None);
    };
    // SAFETY: point is a valid out buffer on the stack; value() only writes
    // it and returns true when the type matches, and only then is the read
    // valid.
    unsafe {
        if value.r#type() != AXValueType::CGPoint {
            return Ok(None);
        }
        let mut point = NSPoint::default();
        if value.value(AXValueType::CGPoint, NonNull::from(&mut point).cast()) {
            Ok(Some(point))
        } else {
            Ok(None)
        }
    }
}

fn ax_size(element: &AXUIElement, attribute: &NSString) -> Result<Option<NSSize>, AXError> {
    let Some(obj) = copy_attr(element, attribute)? else {
        return Ok(None);
    };
    let Some(value) = obj.into_ax_value() else {
        return Ok(None);
    };
    // SAFETY: size is a valid out buffer on the stack; value() only writes it
    // and returns true when the type matches, and only then is the read
    // valid.
    unsafe {
        if value.r#type() != AXValueType::CGSize {
            return Ok(None);
        }
        let mut size = NSSize::default();
        if value.value(AXValueType::CGSize, NonNull::from(&mut size).cast()) {
            Ok(Some(size))
        } else {
            Ok(None)
        }
    }
}

/// Reads an array-typed attribute (AXChildren/AXWindows): returns (array
/// guard, element count).
fn ax_array(
    element: &AXUIElement,
    attribute: &NSString,
) -> Result<Option<(CfObject, usize)>, AXError> {
    let Some(obj) = copy_attr(element, attribute)? else {
        return Ok(None);
    };
    // SAFETY: CFArrayGetTypeID is a pure type query.
    if obj.type_id() != unsafe { CFArrayGetTypeID() } {
        return Ok(None);
    }
    // SAFETY: verified as CFArray; pure count query.
    let count = unsafe { CFArrayGetCount(obj.inner().as_ptr()) };
    if count <= 0 {
        return Ok(None);
    }
    Ok(Some((obj, count as usize)))
}

/// Takes the array's index-th element and retains it as `CFRetained` (under
/// the Get rule the pointer is owned by the array; the extra CFRetain lets
/// the element outlive the array guard and be used independently, replacing
/// the previous bare dereference into the array's internals).
fn array_element_at(array: &CfObject, index: usize) -> Option<CFRetained<AXUIElement>> {
    // SAFETY: array has passed the CFArrayGetTypeID check; index < count is
    // guaranteed by the caller (count comes from CFArrayGetCount on the same
    // array, which is immutable); per the AXChildren/AXWindows contract the
    // elements are AXUIElement; under the Get rule the returned pointer is
    // valid while the array is alive.
    let raw = unsafe { CFArrayGetValueAtIndex(array.inner().as_ptr(), index as isize) };
    let ptr = NonNull::new(raw.cast::<AXUIElement>().cast_mut())?;
    // SAFETY: the element is kept alive by the array guard; AXUIElement is
    // toll-free bridged, and CFRetain/CFRelease are equivalent to its Obj-C
    // retain/release; the extra +1 is released by the returned CFRetained on
    // drop.
    Some(unsafe { CFRetained::retain(ptr) })
}

/// Single-line info for a tree node (position/size are screen point
/// coordinates, consistent with the input coordinate space).
#[derive(Clone)]
struct AxNodeInfo {
    role: String,
    title: String,
    /// subrole: the AXSecureTextField detection signal; kept verbatim to
    /// support the "unreadable" determination.
    subrole: String,
    /// description: the accessible name of web content usually lives here
    /// (the display fallback when title is empty).
    description: String,
    x: i32,
    y: i32,
    width: i32,
    height: i32,
    disabled: bool,
    focused: bool,
    secure: bool,
    /// Whether the geometry fields were actually read (nodes at the depth
    /// limit skip the four geometry IPCs — their x/y/w/h stay zeroed without
    /// meaning "at the origin").
    geometry_read: bool,
}

/// Accounting for AX attribute read errors: [`AX_CANNOT_COMPLETE_LIMIT`]
/// consecutive `AXError::CannotComplete` (target process unresponsive/hung)
/// sets poisoned, requesting an abort of the whole tree. Any other read
/// outcome (success, missing attribute, or another error code) resets the
/// counter — CannotComplete should not occur consecutively in a healthy tree,
/// and ordinary apps commonly do not support some attribute.
struct AttrErrors {
    cannot_complete_streak: u32,
    poisoned: bool,
}

impl AttrErrors {
    fn new() -> Self {
        Self {
            cannot_complete_streak: 0,
            poisoned: false,
        }
    }

    fn record(&mut self, err: AXError) {
        if err == AXError::CannotComplete {
            self.cannot_complete_streak += 1;
            if self.cannot_complete_streak >= AX_CANNOT_COMPLETE_LIMIT {
                self.poisoned = true;
            }
        } else {
            self.cannot_complete_streak = 0;
        }
    }

    fn record_ok(&mut self) {
        self.cannot_complete_streak = 0;
    }
}

/// Single-attribute read for tree traversal: errors are booked and the value
/// degrades to None (the tree is never interrupted by a single attribute
/// failure); success resets the consecutive CannotComplete counter.
fn tree_attr<T>(
    errors: &mut AttrErrors,
    read: impl FnOnce() -> Result<Option<T>, AXError>,
) -> Option<T> {
    match read() {
        Ok(value) => {
            errors.record_ok();
            value
        }
        Err(err) => {
            errors.record(err);
            None
        }
    }
}

/// Reads a node's display fields. Attributes are read one by one: the
/// batch-read API AXUIElementCopyMultipleAttributeValues requires
/// constructing a CFArray<CFString> whose generic default parameters are
/// crate-private types that cannot be constructed externally, so the binding
/// layer does not support batch reads (the performance cost is bounded by the
/// 2s message timeout + the aggregate deadline + the depth/node budgets).
/// Read errors are booked via `errors` and degrade to default values — the
/// tree traversal is never interrupted by a single attribute failure (except
/// consecutive CannotComplete).
///
/// With `with_geometry` false, the four position/size/enabled/focused reads
/// are skipped (for nodes already at the depth limit that will not be drilled
/// into: those fields only affect that row's display, the row renders its
/// geometry as unknown, saving 4 cross-process IPCs).
fn read_node_info(
    element: &AXUIElement,
    names: &AxNames,
    errors: &mut AttrErrors,
    with_geometry: bool,
) -> AxNodeInfo {
    let role = tree_attr(errors, || ax_string(element, &names.role)).unwrap_or_default();
    let title = tree_attr(errors, || ax_string(element, &names.title)).unwrap_or_default();
    let subrole = tree_attr(errors, || ax_string(element, &names.subrole)).unwrap_or_default();
    let description =
        tree_attr(errors, || ax_string(element, &names.description)).unwrap_or_default();
    let (point, size, enabled, focused) = if with_geometry {
        (
            tree_attr(errors, || ax_point(element, &names.position)),
            tree_attr(errors, || ax_size(element, &names.size)),
            tree_attr(errors, || ax_bool(element, &names.enabled)),
            tree_attr(errors, || ax_bool(element, &names.focused)),
        )
    } else {
        (None, None, None, None)
    };
    AxNodeInfo {
        secure: is_secure_text(&role, &subrole),
        role,
        title,
        subrole,
        description,
        x: point.map_or(0, |p| p.x.round() as i32),
        y: point.map_or(0, |p| p.y.round() as i32),
        width: size.map_or(0, |s| s.width.round().max(0.0) as i32),
        height: size.map_or(0, |s| s.height.round().max(0.0) as i32),
        disabled: enabled == Some(false),
        focused: focused == Some(true),
        geometry_read: with_geometry,
    }
}

/// When role, subrole, and description of a hit/focused element are all
/// unreadable, it is treated as an "unreadable node" (fail-closed): a healthy
/// accessibility node exposes at least role; letting an element whose
/// attributes are completely unreadable through as a normal element would let
/// the T3 denylist and safety decisions pass on empty information (review
/// defect 3: an ax_string failure used to be silently flattened by
/// unwrap_or_default).
fn ensure_readable(info: &AxNodeInfo) -> Result<(), ComputerUseError> {
    if info.role.is_empty() && info.subrole.is_empty() && info.description.is_empty() {
        return Err(ComputerUseError::failed(
            "element attributes unreadable (role, subrole and description all missing)",
        ));
    }
    Ok(())
}

/// `AxNodeInfo` → `ElementInfo`. name takes title, falling back to
/// description when empty — the accessible name of browser web content
/// usually lives only on AXDescription.
fn element_info_from(info: AxNodeInfo) -> ElementInfo {
    let name = if info.title.is_empty() {
        info.description
    } else {
        info.title
    };
    let display_name = sanitize_name(&name, MAX_NODE_NAME_CHARS);
    ElementInfo {
        role: info.role,
        screening_name: screening_name(&name, &display_name),
        name: display_name,
        x: info.x,
        y: info.y,
        width: info.width,
        height: info.height,
        secure: info.secure,
    }
}

/// Node budget, overall deadline, and error bookkeeping for tree
/// serialization.
struct TreeWriter {
    next_index: u32,
    remaining: u32,
    truncated: bool,
    /// Overall traversal deadline (absolute instant). The per-call message
    /// timeout only bounds a single IPC; the total for hundreds of nodes
    /// needs its own bound, otherwise the worker thread can be pinned for a
    /// very long time.
    deadline: Instant,
    /// AX attribute read error bookkeeping (aborts on consecutive
    /// CannotComplete).
    errors: AttrErrors,
}

impl TreeWriter {
    /// Allocates the next node index; sets truncated and returns None when
    /// the node budget is exhausted.
    fn take_node(&mut self) -> Option<u32> {
        if self.remaining == 0 {
            self.truncated = true;
            return None;
        }
        self.remaining -= 1;
        let index = self.next_index;
        self.next_index += 1;
        Some(index)
    }

    /// Whether the overall deadline has passed; sets truncated when it has
    /// (the abort signal is carried by truncated).
    fn past_deadline(&mut self) -> bool {
        let past = Instant::now() >= self.deadline;
        if past {
            self.truncated = true;
        }
        past
    }
}

/// Single-line format: `[i] role "title" (x,y,w,h) flags`; flags omitted when
/// none.
fn format_tree_line(index: u32, depth: u32, info: &AxNodeInfo) -> String {
    let mut flags = String::new();
    if info.disabled {
        flags.push_str(" disabled");
    }
    if info.focused {
        flags.push_str(" focused");
    }
    if info.secure {
        flags.push_str(" password");
    }
    // The accessible name of web content (browsers/Electron) usually lives
    // on AXDescription: when title is empty, display description and keep the
    // line format unchanged (review defect T3-Web).
    let display_title = if info.title.is_empty() {
        &info.description
    } else {
        &info.title
    };
    let mut line = String::new();
    let geometry = if info.geometry_read {
        format!("({},{},{},{})", info.x, info.y, info.width, info.height)
    } else {
        "(-,-,-,-)".to_string()
    };
    let _ = write!(
        line,
        "{indent}[{index}] {role} \"{title}\" {geometry}{flags}",
        indent = "  ".repeat(depth as usize),
        // AXRole/AXSubrole are free-form strings supplied by the target app;
        // without sanitizing they could break the one-node-per-line invariant
        // (forged tree lines / newline injection) (round-10 review m6).
        role = sanitize_name(&info.role, MAX_NODE_NAME_CHARS),
        title = sanitize_name(display_title, MAX_NODE_NAME_CHARS),
    );
    line
}

fn write_tree_node(
    element: &AXUIElement,
    depth: u32,
    max_depth: u32,
    names: &AxNames,
    writer: &mut TreeWriter,
    out: &mut String,
) {
    // Aggregate deadline: abort as soon as it is reached (past_deadline
    // already set truncated); the subtree written so far remains valid.
    // Honest overshoot bound: the deadline is only checked at node entry,
    // while a single AX attribute read can block up to
    // AX_MESSAGING_TIMEOUT_SECS and a node performs several reads after the
    // check — so the wall clock can exceed AX_TREE_TIME_LIMIT by up to one
    // node's remaining reads (~+2 s typical). A hung app is cut short
    // mid-node by the consecutive-CannotComplete poison below before it can
    // burn a full message timeout on every remaining attribute.
    if writer.past_deadline() {
        return;
    }
    let Some(index) = writer.take_node() else {
        return;
    };
    // Nodes at the depth limit are not drilled into; the four
    // position/size/enabled/focused reads are skipped.
    let info = read_node_info(element, names, &mut writer.errors, depth < max_depth);
    let _ = writeln!(out, "{}", format_tree_line(index, depth, &info));
    // Consecutive CannotComplete means the target process is hung: abort the
    // whole tree and set truncated, avoiding burning a message timeout per
    // attribute on an unresponsive app.
    if writer.errors.poisoned {
        writer.truncated = true;
        return;
    }
    if depth >= max_depth {
        return;
    }
    match ax_array(element, &names.children) {
        Ok(Some((children, count))) => {
            for i in 0..count {
                let Some(child) = array_element_at(&children, i) else {
                    continue;
                };
                // The element may be destroyed mid-traversal or its attribute
                // reads may fail: truncated carries the abort signal
                // uniformly (budget exhausted / deadline / consecutive
                // CannotComplete).
                write_tree_node(&child, depth + 1, max_depth, names, writer, out);
                if writer.truncated {
                    break;
                }
            }
        }
        // No children (a leaf or the attribute is missing): treat as "this
        // branch ends"; when the children read hits the consecutive
        // CannotComplete threshold, truncated is set immediately, aborting
        // the whole tree.
        Ok(None) => {}
        Err(err) => {
            writer.errors.record(err);
            if writer.errors.poisoned {
                writer.truncated = true;
            }
        }
    }
}

/// The tree root: the focused application's focused window; when the app has
/// no focused window (hidden/menu-bar-only) or the read fails, degrade to the
/// application root (including the menu bar etc., bounded by the depth/node
/// budgets).
fn focused_window_root(system: &AXUIElement, names: &AxNames) -> Option<CFRetained<AXUIElement>> {
    let app = match ax_ui_element(system, &names.focused_application) {
        Ok(Some(app)) => app,
        // No focused application: the tree is unavailable.
        _ => return None,
    };
    match ax_ui_element(&app, &names.focused_window) {
        Ok(Some(window)) => Some(window),
        _ => Some(app),
    }
}

pub(super) struct MacosComputerUseBackend {
    /// Lazy construction: without an Accessibility grant, Enigo::new fails
    /// outright, so construction is deferred to the first keyboard/wheel
    /// action — grant-free capabilities like screenshot/cursor remain usable
    /// while the permission is missing, and a late grant does not leave the
    /// whole backend sticky-failed (backend factory failures are sticky).
    /// **Carries only the keyboard (key/text) and the wheel**: mouse events
    /// (move/click/drag) are all posted as native CGEvents via
    /// [`Self::post_mouse_event`] — enigo 0.6.1's `button()`/`move_mouse()`
    /// depend on `location()`, which flips NSEvent **point** coordinates by
    /// the CGDisplay **physical pixel** height, landing off-screen (clicking
    /// the wrong spot) on Retina/multi-monitor; the latest crates.io release
    /// (0.6.1) has no fix.
    enigo: Option<Enigo>,
    /// The target point (point coordinates) where the most recent synthetic
    /// move settled; the basis for click/mouse_down landing and the landing
    /// guard. Clicks land at the system's current mouse position: the user
    /// physically moving the mouse races our synthetic move (review defect
    /// 6), so the position is verified and re-located before clicking.
    pending_move_target: Option<(i32, i32)>,
    /// Cancel flag set after the caller times out: chunked type injection
    /// checks it between runs, so abandoned requests stop injecting.
    cancel: Option<Arc<AtomicBool>>,
    /// Buttons this backend itself holds synthetically pressed:
    /// `move_to` must post MouseMoved, but a move posted while a button is
    /// held would compose a plain click on apps that only recognize the
    /// Dragged event types, so a held button switches moves to the matching
    /// Dragged event type.
    held_buttons: Vec<MouseButton>,
}

impl MacosComputerUseBackend {
    fn new() -> Self {
        Self {
            enigo: None,
            pending_move_target: None,
            cancel: None,
            held_buttons: Vec::new(),
        }
    }

    /// Gets the input injector. Returns an explicit error without an
    /// Accessibility grant — unauthorized CGEventPost is silently dropped by
    /// WindowServer, so the preflight is a required part of correctness.
    fn enigo(&mut self) -> Result<&mut Enigo, ComputerUseError> {
        if !accessibility_granted() {
            return Err(accessibility_error());
        }
        if self.enigo.is_none() {
            // open_prompt_to_get_permissions=false: permission onboarding
            // goes through request_permissions() uniformly; the tool path
            // only returns explicit errors and never shows a system dialog.
            let settings = Settings {
                open_prompt_to_get_permissions: false,
                ..Settings::default()
            };
            self.enigo = Some(Enigo::new(&settings).map_err(|err| {
                ComputerUseError::unavailable(format!(
                    "cannot initialize CGEvent input backend: {err}"
                ))
            })?);
        }
        match self.enigo.as_mut() {
            Some(enigo) => Ok(enigo),
            None => Err(ComputerUseError::unavailable(
                "CGEvent input backend is not initialized",
            )),
        }
    }

    /// Landing guard before click/press: reads the system cursor's actual
    /// position and, if it deviates from the most recent synthetic move
    /// target by more than [`CLICK_POSITION_TOLERANCE_PT`], re-moves to the
    /// target first — clicks land at the system's current mouse position,
    /// which races the user physically moving the mouse. When there is no
    /// trusted target (no move_to yet), the status quo is kept; when the
    /// cursor position cannot be read, it fails explicitly (fail-closed: a
    /// click whose landing spot is unknown must not proceed).
    ///
    /// Returns `Ok(true)` when the pointer was re-located: the re-move is
    /// already followed by the [`CLICK_SETTLE_MS`] settle pause here, so the
    /// caller must skip its own settle sleep (a corrected click used to
    /// settle twice, 60 ms instead of 30 ms). `Ok(false)` means no
    /// re-location happened and the caller still owes the one settle pause.
    fn guard_click_position(&mut self) -> Result<bool, ComputerUseError> {
        let Some(target) = self.pending_move_target else {
            return Ok(false);
        };
        let (cx, cy) = cursor_points()?;
        // i64 intermediate: with target/cursor coordinates near i32::MIN/MAX
        // (never reachable by a real cursor, but cursor_points() does not
        // clamp) the i32 subtraction would overflow and panic in debug builds.
        let dx = (i64::from(cx) - i64::from(target.0)).abs();
        let dy = (i64::from(cy) - i64::from(target.1)).abs();
        if dx <= i64::from(CLICK_POSITION_TOLERANCE_PT)
            && dy <= i64::from(CLICK_POSITION_TOLERANCE_PT)
        {
            return Ok(false);
        }
        self.post_move(target)?;
        sleep(Duration::from_millis(CLICK_SETTLE_MS));
        Ok(true)
    }

    /// Landing spot for coordinate-less click/press/release: prefer the most
    /// recent synthetic move target (trusted), otherwise use the system
    /// cursor's actual position (readable without a grant).
    fn click_destination(&self) -> Result<(i32, i32), ComputerUseError> {
        match self.pending_move_target {
            Some(target) => Ok(target),
            None => cursor_points(),
        }
    }

    /// Synthesizes one mouse event (CGEventPost at kCGHIDEventTap, the same
    /// injection location as enigo). With `click_state > 0`,
    /// kCGMouseEventClickState is attached — the basis for double/triple-click
    /// recognition. Without Accessibility, CGEventPost is silently dropped, so
    /// preflight first.
    fn post_mouse_event(
        &mut self,
        event_type: u32,
        cg_button: u32,
        at: (i32, i32),
        click_state: i64,
    ) -> Result<(), ComputerUseError> {
        if !accessibility_granted() {
            return Err(accessibility_error());
        }
        // SAFETY: CGEventCreateMouseEvent accepts a NULL source (the default
        // event source); the returned +1 event is used after a null check,
        // CGEventPost consumes without retaining, CFRelease releases exactly
        // once; at is a pure by-value parameter.
        let event = unsafe {
            CGEventCreateMouseEvent(
                std::ptr::null(),
                event_type,
                NSPoint {
                    x: f64::from(at.0),
                    y: f64::from(at.1),
                },
                cg_button,
            )
        };
        if event.is_null() {
            return Err(ComputerUseError::failed(format!(
                "CGEventCreateMouseEvent returned null for event type {event_type}"
            )));
        }
        // SAFETY: event is the valid CGEventRef successfully created above;
        // the click_state field is written per the CG documentation
        // (multi-click count).
        unsafe {
            if click_state > 0 {
                CGEventSetIntegerValueField(event, CG_EVENT_FIELD_CLICK_STATE, click_state);
            }
            CGEventPost(CG_EVENT_TAP_HID, event);
            CFRelease(event);
        }
        Ok(())
    }

    /// Synthesizes one mouse move. While one of this backend's own buttons
    /// is held, the move uses the matching Dragged event type — apps
    /// recognize a drag only via those, not via MouseMoved.
    fn post_move(&mut self, at: (i32, i32)) -> Result<(), ComputerUseError> {
        let (event_type, button) = move_event_type(&self.held_buttons);
        self.post_mouse_event(event_type, button, at, 0)
    }

    /// Presses all keys (rolling back the pressed ones on error), pauses,
    /// then releases in reverse.
    fn chord(&mut self, keys: &[Key], hold: Duration) -> Result<(), ComputerUseError> {
        // Map the whole chord first, then press (review finding: map_key's
        // `?` early return used to skip the rollback on enigo's error path
        // below — for chords like `cmd+plus`, Meta was pressed first and then
        // '+' was rejected by the layout-safe set, stranding Meta and
        // polluting all of enigo's subsequent injections. The module's stated
        // invariant is "best-effort release everything even on a mid-way
        // error", which applies equally to mapping failures).
        let mapped = ordered_chord_keys(keys)
            .iter()
            .map(|key| map_key(*key))
            .collect::<Result<Vec<_>, _>>()?;
        // Clone the flag before enigo(): that accessor returns an &mut Enigo
        // borrowed from self for the rest of the function, so the hold loop
        // below must not read self.cancel through the same borrow (the same
        // ordering as the Linux hold_key).
        let cancel = self.cancel.clone();
        let enigo = self.enigo()?;
        let mut pressed: Vec<enigo::Key> = Vec::with_capacity(mapped.len());
        for key in mapped {
            if let Err(err) = enigo.key(key, Direction::Press) {
                let _ = release_reverse(&pressed, enigo);
                return Err(map_input_err("key press", err));
            }
            pressed.push(key);
        }
        // Chunk the hold so a stop/timeout cancel flag is polled within
        // HOLD_CANCEL_POLL_MS instead of waiting out the whole hold (up to
        // 30 s). The keys are always released, whether the hold ran out or
        // was cancelled.
        let mut remaining = hold;
        while remaining > Duration::ZERO {
            if cancel
                .as_ref()
                .is_some_and(|flag| flag.load(Ordering::SeqCst))
            {
                let _ = release_reverse(&pressed, enigo);
                return Err(ComputerUseError::unavailable(
                    "hold was cancelled (caller timeout or stop); the keys have been released",
                ));
            }
            let step = remaining.min(Duration::from_millis(HOLD_CANCEL_POLL_MS));
            sleep(step);
            remaining -= step;
        }
        release_reverse(&pressed, enigo).map_err(|err| map_input_err("key release", err))
    }

    /// ScreenCaptureKit capture (macOS 15.2+). captureImageInRect returns
    /// physical pixels at the monitor's native scale; the actual scale is
    /// derived backwards from the returned image (points / actual pixel
    /// width) — never trusting the scale_factor estimate, which also holds
    /// for rotated screens/non-integer scales.
    fn capture_via_screen_capture_kit(
        &mut self,
        origin_x: i32,
        origin_y: i32,
        width_points: f64,
        height_points: f64,
    ) -> Result<Capture, ComputerUseError> {
        let shot = super::screen_capture_kit::capture_region(
            origin_x,
            origin_y,
            width_points.round() as i32,
            height_points.round() as i32,
        )?;
        let mut rgba = shot.rgba;
        // ScreenCaptureKit outputs premultiplied alpha; a single pass forces
        // it opaque so downstream PNG encoding does not leak meaningless
        // alpha (the same convention as the xcap fallback path).
        for pixel in rgba.chunks_exact_mut(4) {
            pixel[3] = 255;
        }
        // The scale is derived per axis (review finding: deriving from width
        // alone assumed "the image aspect ratio equals the point aspect
        // ratio"; in SCK/CGWindowList practice the scale is uniform, but
        // per-axis derivation is free and insensitive to that assumption).
        let input_scale_x = width_points / shot.width.max(1) as f64;
        let input_scale_y = height_points / shot.height.max(1) as f64;
        Ok(Capture {
            rgba,
            width: shot.width as u32,
            height: shot.height as u32,
            origin_x,
            origin_y,
            input_scale_x,
            input_scale_y,
        })
    }
}

impl ComputerUseBackend for MacosComputerUseBackend {
    fn capabilities(&self) -> Capabilities {
        Capabilities {
            screenshot: true,
            input: true,
            ui_tree: true,
            notes: "macos: all input coordinates are CGEvent global points (screenshot px / \
                    backing scale factor); mouse events are posted as native CGEvents and \
                    keyboard/wheel go through enigo; Screen Recording + Accessibility TCC \
                    grants are required and usually need an app restart after granting; \
                    macOS 26 (Tahoe) may filter synthetic modifier-key events aimed at global \
                    hotkey listeners; multi-click recognition does not verify that repeated \
                    clicks land on the same point; key-chord characters outside the safe \
                    (US-layout-defined) keyboard set are rejected with an explicit error \
                    instead of injecting a wrong key, but on non-US layouts an in-set \
                    character can still resolve to a different key; typed text is \
                    delivered in 20-character chunks and the OS can silently truncate a \
                    chunk containing many non-BMP characters (e.g. emoji); T3 target \
                    screening relies on the AX tree — \
                    windows that expose no accessibility data (some Electron/web-contents \
                    windows) report no element at the target point, so consequential targets \
                    inside them cannot be recognized and are NOT confirmation-screened"
                .to_string(),
        }
    }

    fn capture(&mut self) -> Result<Capture, ComputerUseError> {
        if !screen_recording_granted() {
            return Err(screen_recording_error());
        }
        let cursor = cursor_points().ok();
        let monitor = pick_monitor(cursor)?;
        // The monitor origin is CGDisplayBounds = points (the input
        // coordinate space); width/height are points too.
        let origin_x = monitor
            .x()
            .map_err(|err| map_xcap_err("monitor origin", err))?;
        let origin_y = monitor
            .y()
            .map_err(|err| map_xcap_err("monitor origin", err))?;
        let width_points = f64::from(
            monitor
                .width()
                .map_err(|err| map_xcap_err("monitor size", err))?,
        );
        let height_points = f64::from(
            monitor
                .height()
                .map_err(|err| map_xcap_err("monitor size", err))?,
        );
        if super::screen_capture_kit::available() {
            // A runtime SCK failure returns the error as-is: there is no
            // fallback to xcap's CGWindowListCreateImage path, because on
            // Sequoia+ that API sits behind the periodic "keep allowing
            // screen recording" system confirmation — surfacing the SCK
            // error is preferable to re-prompting the user on every capture.
            return self.capture_via_screen_capture_kit(
                origin_x,
                origin_y,
                width_points,
                height_points,
            );
        }
        // Fallback below macOS 15.2: xcap's CGWindowListCreateImage path. The
        // screenshot is device physical pixels (xcap already applies the
        // BGRA→RGBA row fix). The actual scale is derived backwards from the
        // returned image (points / actual pixel width) — never trusting the
        // scale_factor estimate, the same policy as the SCK path, which also
        // holds for rotated screens/non-integer scales.
        let image = monitor
            .capture_image()
            .map_err(|err| map_xcap_err("screen capture", err))?;
        let width = image.width();
        let height = image.height();
        // The scale is derived per axis (the same review fix as the SCK
        // path: do not assume the image aspect ratio equals the point aspect
        // ratio).
        let input_scale_x = width_points / f64::from(width.max(1));
        let input_scale_y = height_points / f64::from(height.max(1));
        let mut rgba = image.into_raw();
        // CGWindowListCreateImage's alpha channel depends on the content; a
        // single pass forces it opaque so downstream PNG encoding does not
        // leak meaningless alpha.
        for pixel in rgba.chunks_exact_mut(4) {
            pixel[3] = 255;
        }
        Ok(Capture {
            rgba,
            width,
            height,
            origin_x,
            origin_y,
            input_scale_x,
            input_scale_y,
        })
    }

    fn cursor_position(&mut self) -> Result<(i32, i32), ComputerUseError> {
        // The trait contract wants global input-space coordinates: on macOS
        // that is CGEvent global points, exactly what cursor_points() reads.
        // Points are globally unambiguous across monitors; the former
        // points × monitor-scale "device pixel" value was ill-defined under
        // mixed DPI (per-monitor device rects overlap) and broke downstream
        // containment checks against point-space rects.
        cursor_points()
    }

    fn move_to(&mut self, x: i32, y: i32) -> Result<(), ComputerUseError> {
        // x/y are CGEvent global point coordinates (the tool layer already
        // converted them by input_scale). MouseMoved is posted natively:
        // enigo's move_mouse computes the delta field from a broken
        // location() on Retina.
        self.post_move((x, y))?;
        // Records the trusted landing point, used by the landing guard and
        // landing selection of subsequent click/mouse_down.
        self.pending_move_target = Some((x, y));
        Ok(())
    }

    fn click(&mut self, button: MouseButton, count: u8) -> Result<(), ComputerUseError> {
        // Landing guard first: when the user physically moving the mouse
        // races the synthetic move, the click would land at the user's cursor
        // (review defect 6).
        let re_located = self.guard_click_position()?;
        let dest = self.click_destination()?;
        // Let the earlier move settle before clicking, so the click does not
        // land at the old cursor position. When the guard re-located the
        // pointer it already slept the settle pause, so this is skipped there
        // — every click path settles exactly once.
        if !re_located {
            sleep(Duration::from_millis(CLICK_SETTLE_MS));
        }
        let (down, up, _) = cg_mouse_event_types(button);
        let cg_button = cg_mouse_button(button);
        let rounds = u32::from(count.max(1));
        // Track whether THIS click owns the held_buttons entry: a click issued
        // while mouse_down already holds the same button posts a second down
        // and a single up, so the OS-level press count stays ≥ 1 and the entry
        // must survive. Removing it unconditionally desynced held_buttons
        // (later moves posted MouseMoved instead of LeftMouseDragged and the
        // stranded press hijacked the user's next physical click).
        let we_pressed = !self.held_buttons.contains(&button);
        for i in 0..rounds {
            // clickState increments from 1: the system/app recognizes double
            // and triple clicks from it.
            let click_state = i64::from(i) + 1;
            self.post_mouse_event(down, cg_button, dest, click_state)?;
            if we_pressed {
                self.held_buttons.push(button);
            }
            // A successful down with a failed up (TCC revoked mid-way, event
            // allocation failure) would strand the physical button pressed,
            // hijacking the user's next physical click (review finding) —
            // retry the release once; if it still fails, report "the button
            // may still be pressed" instead of returning silently. The
            // stranded button stays registered in `held_buttons`, so later
            // synthetic moves keep using the Dragged event type.
            if let Err(error) = self.post_mouse_event(up, cg_button, dest, click_state) {
                sleep(Duration::from_millis(MULTI_CLICK_INTERVAL_MS));
                self.post_mouse_event(up, cg_button, dest, click_state)
                    .map_err(|retry| {
                        ComputerUseError::failed(format!(
                            "click release failed twice ({error}; {retry}); \
                             the mouse button may still be pressed"
                        ))
                    })?;
            }
            if we_pressed {
                self.held_buttons.retain(|held| *held != button);
            }
            if i + 1 < rounds {
                sleep(Duration::from_millis(MULTI_CLICK_INTERVAL_MS));
            }
        }
        Ok(())
    }

    fn mouse_down(&mut self, button: MouseButton) -> Result<(), ComputerUseError> {
        // Same landing guard as click: if the press lands in the wrong place,
        // everything downstream (drag/selection) is wrong.
        let re_located = self.guard_click_position()?;
        let dest = self.click_destination()?;
        // Settle exactly once: the guard's re-location path already slept the
        // settle pause (same fix as click()).
        if !re_located {
            sleep(Duration::from_millis(CLICK_SETTLE_MS));
        }
        let (down, _, _) = cg_mouse_event_types(button);
        let posted = self.post_mouse_event(down, cg_mouse_button(button), dest, 1);
        if posted.is_ok() && !self.held_buttons.contains(&button) {
            self.held_buttons.push(button);
        }
        posted
    }

    fn mouse_up(&mut self, button: MouseButton) -> Result<(), ComputerUseError> {
        // Release does no landing guard/re-location (the up of down→move→up
        // must land at the drag endpoint).
        let dest = self.click_destination()?;
        let (_, up, _) = cg_mouse_event_types(button);
        let posted = self.post_mouse_event(up, cg_mouse_button(button), dest, 1);
        if posted.is_ok() {
            self.held_buttons.retain(|held| *held != button);
        }
        posted
    }

    fn drag(&mut self, from: (i32, i32), to: (i32, i32)) -> Result<(), ComputerUseError> {
        let (down, up, dragged) = cg_mouse_event_types(MouseButton::Left);
        let left = cg_mouse_button(MouseButton::Left);
        self.post_move(from)?;
        sleep(Duration::from_millis(CLICK_SETTLE_MS));
        self.post_mouse_event(down, left, from, 1)?;
        if !self.held_buttons.contains(&MouseButton::Left) {
            self.held_buttons.push(MouseButton::Left);
        }
        sleep(Duration::from_millis(DRAG_PRESS_SETTLE_MS));
        let result = (|| {
            for (x, y) in drag_waypoints(from, to, DRAG_STEPS) {
                // Same abandonment contract as type_text and the Linux drag:
                // a request the caller already abandoned must stop at the
                // next waypoint — otherwise it keeps holding the physical
                // button for the whole interpolated path. The common release
                // below always runs.
                if self
                    .cancel
                    .as_ref()
                    .is_some_and(|flag| flag.load(Ordering::SeqCst))
                {
                    return Err(ComputerUseError::unavailable(
                        "drag was cancelled (caller timeout or stop); the button is \
                         released and the pointer stays at the last waypoint",
                    ));
                }
                // Send LeftMouseDragged while held (some apps only recognize
                // the dragged type).
                self.post_mouse_event(dragged, left, (x, y), 1)?;
                sleep(Duration::from_millis(DRAG_STEP_DELAY_MS));
            }
            Ok(())
        })();
        // The button must be released regardless of whether the path
        // movement errored, so the mouse is not left stuck pressed.
        // Inspect both results instead of `Result::and`, which keeps only the
        // first error: when the release fails too, the caller must still
        // learn that the button may be stranded pressed (mirrors click()'s
        // stranded-button wording).
        let release = self.post_mouse_event(up, left, to, 1);
        if release.is_ok() {
            self.held_buttons.retain(|held| *held != MouseButton::Left);
        }
        match (result, release) {
            (Ok(()), Ok(())) => {}
            // Only the path move failed and the release succeeded: report the
            // move error unchanged.
            (Err(move_error), Ok(())) => return Err(move_error),
            (Ok(()), Err(release)) => {
                return Err(ComputerUseError::failed(format!(
                    "drag release failed ({release}); the mouse button may still be pressed"
                )));
            }
            (Err(move_error), Err(release)) => {
                return Err(ComputerUseError::failed(format!(
                    "drag move failed ({move_error}); its release also failed ({release}); \
                     the mouse button may still be pressed"
                )));
            }
        }
        // The drag endpoint is where the cursor lands; refresh the trusted
        // landing point (the start move does not change it).
        self.pending_move_target = Some(to);
        Ok(())
    }

    fn scroll(&mut self, direction: ScrollDirection, clicks: u32) -> Result<(), ComputerUseError> {
        let (axis, length) = map_scroll(direction, clicks);
        self.enigo()?
            .scroll(length, axis)
            .map_err(|err| map_input_err("scroll", err))
    }

    fn type_text(&mut self, text: &str) -> Result<(), ComputerUseError> {
        // Direct Unicode injection (CGEventKeyboardSetUnicodeString; enigo
        // chunks internally at 20 characters), bypassing the IME — text lands
        // directly in the focused field. Chunked injection with between-run
        // cancel checks: low-level event hooks process each event
        // synchronously, so long text can legitimately exceed the call
        // budget — the checks shrink the upper bound of zombie injection
        // after a caller timeout from the whole text to one run. CR/CRLF is
        // normalized to '\n' first (the shared helper; a raw CR injected via
        // CGEventKeyboardSetUnicodeString renders as a line break on top of
        // the real Return click, so CRLF text double-broke/double-submitted
        // where Windows/Linux normalize). Newlines and tabs are split out
        // as real Return/Tab key clicks, the same shape as the Windows/Linux
        // backends: enigo's macOS fast_text handles a leading '\n' by
        // recursively injecting "\u{200B}\n" (zero-width space +
        // newline), which would pollute the target field (a password box
        // especially) with invisible characters.
        let text = normalize_typed_newlines(text);
        for run in split_type_runs(&text, TYPE_CHUNK_CHARS) {
            if let Some(flag) = &self.cancel {
                if flag.load(Ordering::SeqCst) {
                    return Err(ComputerUseError::unavailable(
                        "type text was cancelled (caller timeout or stop); characters \
                         already injected are not undone",
                    ));
                }
            }
            let injector = self.enigo()?;
            let result = match run {
                TypeRun::Text(chunk) => injector
                    .text(&chunk)
                    .map_err(|err| map_input_err("type text", err)),
                TypeRun::Return => injector
                    .key(enigo::Key::Return, Direction::Click)
                    .map_err(|err| map_input_err("type text newline", err)),
                TypeRun::Tab => injector
                    .key(enigo::Key::Tab, Direction::Click)
                    .map_err(|err| map_input_err("type text tab", err)),
            };
            result?;
        }
        Ok(())
    }

    fn set_cancel_flag(&mut self, flag: Option<Arc<AtomicBool>>) {
        self.cancel = flag;
    }

    fn key_chord(&mut self, keys: &[Key]) -> Result<(), ComputerUseError> {
        self.chord(keys, Duration::from_millis(CHORD_HOLD_MS))
    }

    fn hold_key(&mut self, keys: &[Key], ms: u64) -> Result<(), ComputerUseError> {
        self.chord(keys, Duration::from_millis(ms))
    }

    fn ui_tree(&mut self, opts: &UiTreeOptions) -> Result<String, ComputerUseError> {
        if !accessibility_granted() {
            return Err(accessibility_error());
        }
        let max_depth = opts
            .max_depth
            .unwrap_or(DEFAULT_TREE_MAX_DEPTH)
            .min(MAX_TREE_DEPTH);
        let max_nodes = opts
            .max_nodes
            .unwrap_or(DEFAULT_TREE_MAX_NODES)
            .min(MAX_TREE_NODES);
        let names = AxNames::new();
        // SAFETY: AXUIElementCreateSystemWide is callable on any thread; the
        // crate guarantees a non-null return, the retain count is managed by
        // CFRetained; the object never leaves this call/thread.
        let system = unsafe { AXUIElement::new_system_wide() };
        // SAFETY: system is a valid system-wide AXUIElement; setting the
        // global message timeout keeps heavy apps' synchronous IPC from
        // dragging down the worker thread. Failures are ignored (falls back
        // to the default timeout).
        let _ = unsafe { system.set_messaging_timeout(AX_MESSAGING_TIMEOUT_SECS) };
        let Some(root) = focused_window_root(&system, &names) else {
            return Err(ComputerUseError::unavailable(
                "no focused application is available for ui_tree",
            ));
        };
        let mut out = String::new();
        let mut writer = TreeWriter {
            next_index: 0,
            remaining: max_nodes,
            truncated: false,
            // Aggregate deadline: hundreds of nodes × multiple attribute
            // reads have a worst-case total far beyond a single message
            // timeout.
            deadline: Instant::now() + AX_TREE_TIME_LIMIT,
            errors: AttrErrors::new(),
        };
        write_tree_node(&root, 0, max_depth, &names, &mut writer, &mut out);
        if writer.truncated {
            // Label the abort reason faithfully: the target hung (consecutive
            // CannotComplete) / timeout / node budget exhausted.
            let reason = if writer.errors.poisoned {
                "the focused application stopped responding"
            } else if Instant::now() >= writer.deadline {
                "the traversal time budget was exceeded"
            } else {
                "the node budget was exhausted"
            };
            let _ = writeln!(
                out,
                "... (truncated after {} nodes: {reason}; pass a larger max_nodes to see more)",
                writer.next_index
            );
        }
        Ok(out)
    }

    fn element_at_point(
        &mut self,
        x: i32,
        y: i32,
    ) -> Result<Option<ElementInfo>, ComputerUseError> {
        if !accessibility_granted() {
            return Err(accessibility_error());
        }
        let names = AxNames::new();
        // SAFETY: same as ui_tree.
        let system = unsafe { AXUIElement::new_system_wide() };
        // SAFETY: same as ui_tree.
        let _ = unsafe { system.set_messaging_timeout(AX_MESSAGING_TIMEOUT_SECS) };
        let mut raw: *const AXUIElement = std::ptr::null();
        let Some(out) = NonNull::new(&mut raw) else {
            return Err(ComputerUseError::failed(
                "cannot create out pointer for element hit-test",
            ));
        };
        // SAFETY: out points at a valid out pointer on this function's stack;
        // x/y are CGEvent global point coordinates, matching the top-left
        // screen point coordinates AXUIElementCopyElementAtPosition expects
        // (that API hit-tests by window z-order internally); use the output
        // only when Success is returned and it is non-null.
        let err = unsafe { system.copy_element_at_position(x as f32, y as f32, out) };
        match err {
            AXError::Success => {}
            // No AX object at that point (desktop gaps etc.).
            AXError::NoValue => return Ok(None),
            other => {
                return Err(ComputerUseError::failed(format!(
                    "AXUIElementCopyElementAtPosition failed: AXError({})",
                    other.0
                )));
            }
        }
        let ptr = NonNull::new(raw.cast::<c_void>().cast_mut())
            .ok_or_else(|| ComputerUseError::failed("element hit-test returned a null element"))?;
        // After type verification, convert into a typed CFRetained (no more
        // raw-pointer dereferences).
        let element = CfObject(ptr).into_ui_element().ok_or_else(|| {
            ComputerUseError::failed("element hit-test returned an unexpected CF type")
        })?;
        let mut errors = AttrErrors::new();
        let info = read_node_info(&element, &names, &mut errors, true);
        // When role/subrole/description of the hit element are all
        // unreadable, treat it as unreadable (fail-closed): prefer an
        // explicit error over ever returning a partial element — partial
        // information would be treated downstream as decidable screening
        // input.
        ensure_readable(&info)?;
        Ok(Some(element_info_from(info)))
    }

    fn focused_element(&mut self) -> Result<Option<ElementInfo>, ComputerUseError> {
        if !accessibility_granted() {
            return Err(accessibility_error());
        }
        let names = AxNames::new();
        // SAFETY: same as ui_tree.
        let system = unsafe { AXUIElement::new_system_wide() };
        // SAFETY: same as ui_tree.
        let _ = unsafe { system.set_messaging_timeout(AX_MESSAGING_TIMEOUT_SECS) };
        // Walk down the focus chain level by level: system →
        // AXFocusedApplication → AXFocusedWindow → AXFocusedUIElement. Return
        // Ok(None) when there is no focused application/window/element; any
        // AX error at any level fails explicitly (fail-closed) — never guess
        // an element that is "probably the focus".
        let app = match ax_ui_element(&system, &names.focused_application) {
            Ok(Some(app)) => app,
            Ok(None) => return Ok(None),
            Err(err) => return Err(focused_chain_error("AXFocusedApplication", err)),
        };
        let window = match ax_ui_element(&app, &names.focused_window) {
            Ok(Some(window)) => window,
            Ok(None) => return Ok(None),
            Err(err) => return Err(focused_chain_error("AXFocusedWindow", err)),
        };
        let element = match ax_ui_element(&window, &names.focused_ui_element) {
            Ok(Some(element)) => element,
            Ok(None) => return Ok(None),
            Err(err) => return Err(focused_chain_error("AXFocusedUIElement", err)),
        };
        let mut errors = AttrErrors::new();
        let info = read_node_info(&element, &names, &mut errors, true);
        // The same unreadable determination as element_at_point: all-empty
        // attributes never construct an ElementInfo.
        ensure_readable(&info)?;
        Ok(Some(element_info_from(info)))
    }
}

pub(super) fn create_backend() -> Result<Box<dyn ComputerUseBackend>, ComputerUseError> {
    Ok(Box::new(MacosComputerUseBackend::new()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn key_mapping_covers_named_keys_and_functions() {
        use enigo::Key as EK;
        let cases: &[(Key, EK)] = &[
            (Key::Control, EK::Control),
            (Key::Alt, EK::Alt),
            (Key::Shift, EK::Shift),
            (Key::Meta, EK::Meta),
            (Key::Enter, EK::Return),
            (Key::Escape, EK::Escape),
            (Key::Tab, EK::Tab),
            (Key::Space, EK::Space),
            (Key::Backspace, EK::Backspace),
            (Key::Delete, EK::Delete),
            // macOS has no Insert variant; maps to the HELP keycode (the key
            // at the Insert position).
            (Key::Insert, EK::Help),
            (Key::Up, EK::UpArrow),
            (Key::Down, EK::DownArrow),
            (Key::Left, EK::LeftArrow),
            (Key::Right, EK::RightArrow),
            (Key::Home, EK::Home),
            (Key::End, EK::End),
            (Key::PageUp, EK::PageUp),
            (Key::PageDown, EK::PageDown),
            (Key::Function(1), EK::F1),
            (Key::Function(6), EK::F6),
            (Key::Function(12), EK::F12),
        ];
        for (input, expected) in cases {
            assert_eq!(map_key(*input).ok(), Some(*expected), "mapping {input:?}");
        }
        assert_eq!(map_key(Key::Char('s')).ok(), Some(EK::Unicode('s')));
        // Out-of-layout characters fail explicitly (enigo would degrade to
        // keycode 0 = ANSI 'a' and inject the wrong key).
        assert!(map_key(Key::Char('中')).is_err());
        assert!(map_key(Key::Char('\u{1F600}')).is_err());
        // Shift-state characters are rejected too: after the reverse lookup
        // enigo omits the Shift flag and injects the unshifted wrong
        // character ('+' would actually type '=').
        assert!(map_key(Key::Char('+')).is_err());
        assert!(map_key(Key::Char('A')).is_err());
        // US-layout characters that need no Shift still map directly.
        assert_eq!(map_key(Key::Char('/')).ok(), Some(EK::Unicode('/')));
        assert_eq!(map_key(Key::Char('-')).ok(), Some(EK::Unicode('-')));
        assert!(map_key(Key::Function(0)).is_err());
        assert!(map_key(Key::Function(13)).is_err());
    }

    #[test]
    fn layout_safe_chars_match_unshifted_us_keys() {
        // Every US-layout character typeable without Shift is allowed.
        for c in "az09 `-=[]\\;',./".chars() {
            assert!(is_layout_safe_char(c), "{c:?} must be layout-safe");
        }
        assert!(is_layout_safe_char(' '));
        // Uppercase letters, Shift-combined punctuation, and non-ASCII are
        // all rejected.
        for c in [
            'A', 'Z', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '{', '}', '|',
            ':', '"', '<', '>', '?', '~', '中', '\n',
        ] {
            assert!(!is_layout_safe_char(c), "{c:?} must be rejected");
        }
    }

    #[test]
    fn consecutive_cannot_complete_poisons_and_other_results_reset() {
        let mut errors = AttrErrors::new();
        errors.record(AXError::CannotComplete);
        errors.record(AXError::CannotComplete);
        assert!(!errors.poisoned);
        // Other outcomes (success/ordinary error codes) reset the consecutive
        // counter.
        errors.record(AXError::AttributeUnsupported);
        errors.record_ok();
        errors.record(AXError::CannotComplete);
        errors.record(AXError::CannotComplete);
        assert!(!errors.poisoned);
        errors.record(AXError::CannotComplete);
        assert!(
            errors.poisoned,
            "three consecutive CannotComplete must poison the traversal"
        );
    }

    #[test]
    fn tree_writer_flags_truncation_on_budget_and_deadline() {
        let mut writer = TreeWriter {
            next_index: 0,
            remaining: 2,
            truncated: false,
            deadline: Instant::now() + AX_TREE_TIME_LIMIT,
            errors: AttrErrors::new(),
        };
        assert!(!writer.past_deadline());
        assert_eq!(writer.take_node(), Some(0));
        assert_eq!(writer.take_node(), Some(1));
        // Node budget exhausted: truncated is set and no further indices are
        // allocated.
        assert_eq!(writer.take_node(), None);
        assert!(writer.truncated);

        let mut expired = TreeWriter {
            next_index: 0,
            remaining: 10,
            truncated: false,
            // Instant subtraction panics on overflow instead of wrapping, so
            // checked_sub builds the past instant.
            deadline: Instant::now()
                .checked_sub(Duration::from_secs(1))
                .expect("a past instant exists on any platform with a clock"),
            errors: AttrErrors::new(),
        };
        assert!(expired.past_deadline());
        assert!(expired.truncated);
    }

    #[test]
    fn element_info_prefers_title_and_rejects_unreadable_nodes() {
        let base = AxNodeInfo {
            role: "AXButton".to_string(),
            title: String::new(),
            subrole: String::new(),
            // Web content: the accessible name lives only in description.
            description: "Submit search".to_string(),
            x: 1,
            y: 2,
            width: 3,
            height: 4,
            disabled: false,
            focused: false,
            secure: false,
            geometry_read: true,
        };
        assert!(ensure_readable(&base).is_ok());
        let info = element_info_from(base.clone());
        assert_eq!(info.name, "Submit search");
        assert_eq!(info.role, "AXButton");
        let titled = AxNodeInfo {
            title: "确定".to_string(),
            ..base.clone()
        };
        assert_eq!(element_info_from(titled).name, "确定");
        // role/subrole/description all empty → unreadable, fail-closed.
        let unreadable = AxNodeInfo {
            role: String::new(),
            title: String::new(),
            subrole: String::new(),
            description: String::new(),
            ..base
        };
        assert!(ensure_readable(&unreadable).is_err());
    }

    #[test]
    fn tree_line_falls_back_to_description_for_web_nodes() {
        let web_button = AxNodeInfo {
            role: "AXButton".to_string(),
            title: String::new(),
            subrole: String::new(),
            description: "Search the web".to_string(),
            x: 10,
            y: 20,
            width: 100,
            height: 24,
            disabled: false,
            focused: true,
            secure: false,
            geometry_read: true,
        };
        let line = format_tree_line(7, 2, &web_button);
        assert!(
            line.contains("[7] AXButton \"Search the web\" (10,20,100,24) focused"),
            "unexpected line: {line}"
        );
        // Review finding: a node whose geometry was skipped (depth limit)
        // must not render as a fake origin "(0,0,0,0)" — the model would
        // click (0,0) on it. It renders as unknown instead.
        let mut unprobed = web_button.clone();
        unprobed.geometry_read = false;
        let line = format_tree_line(9, 3, &unprobed);
        assert!(
            line.contains("[9] AXButton \"Search the web\" (-,-,-,-) focused"),
            "unexpected line: {line}"
        );
        // When title is non-empty it is still displayed, format unchanged.
        let titled = AxNodeInfo {
            title: "Native".to_string(),
            ..web_button
        };
        let line = format_tree_line(8, 0, &titled);
        assert!(
            line.contains("[8] AXButton \"Native\" (10,20,100,24) focused"),
            "unexpected line: {line}"
        );
    }

    #[test]
    fn cg_mouse_event_mapping_matches_core_graphics_constants() {
        // Raw values pinned against the CGEventType/CGMouseButton enums
        // (vendored core-graphics 0.25 src/event.rs).
        assert_eq!(cg_mouse_button(MouseButton::Left), 0);
        assert_eq!(cg_mouse_button(MouseButton::Right), 1);
        assert_eq!(cg_mouse_button(MouseButton::Middle), 2);
        assert_eq!(cg_mouse_event_types(MouseButton::Left), (1, 2, 6));
        assert_eq!(cg_mouse_event_types(MouseButton::Right), (3, 4, 7));
        // Middle = kCGEventOtherMouseDown/Up/Dragged = 25/26/27; 21 is
        // undefined and 22 is kCGEventScrollWheel.
        assert_eq!(cg_mouse_event_types(MouseButton::Middle), (25, 26, 27));
    }

    #[test]
    fn secure_text_detection_covers_role_and_subrole() {
        assert!(is_secure_text("AXTextField", "AXSecureTextField"));
        assert!(is_secure_text("AXSecureTextField", ""));
        assert!(!is_secure_text("AXTextField", ""));
        assert!(!is_secure_text("AXButton", ""));
    }

    #[test]
    #[ignore = "live probe: needs Accessibility TCC grant and a real focused UI element"]
    fn live_focused_element_returns_element_with_role() {
        if !accessibility_granted() {
            return;
        }
        let mut backend = MacosComputerUseBackend::new();
        let focused = backend
            .focused_element()
            .expect("focused_element must not fail on a granted desktop");
        let info = focused.expect("a real desktop session always has a focused element");
        assert!(
            !info.role.is_empty(),
            "focused element role must not be empty"
        );
    }

    /// Review finding: a synthetic move while one of this backend's own
    /// buttons is held must use the matching Dragged event type, otherwise
    /// apps treat the down → move → up sequence as a plain click.
    #[test]
    fn move_event_type_follows_held_buttons() {
        assert_eq!(
            move_event_type(&[]),
            (CG_EVENT_MOUSE_MOVED, CG_MOUSE_BUTTON_LEFT),
            "no held button: plain move"
        );
        assert_eq!(
            move_event_type(&[MouseButton::Left]),
            (CG_EVENT_LEFT_MOUSE_DRAGGED, CG_MOUSE_BUTTON_LEFT)
        );
        assert_eq!(
            move_event_type(&[MouseButton::Right]),
            (
                CG_EVENT_RIGHT_MOUSE_DRAGGED,
                cg_mouse_button(MouseButton::Right)
            )
        );
        assert_eq!(
            move_event_type(&[MouseButton::Middle]),
            (
                CG_EVENT_OTHER_MOUSE_DRAGGED,
                cg_mouse_button(MouseButton::Middle)
            )
        );
        // Left wins when several buttons report held: it is the drag case
        // that matters in practice.
        assert_eq!(
            move_event_type(&[MouseButton::Middle, MouseButton::Left]),
            (CG_EVENT_LEFT_MOUSE_DRAGGED, CG_MOUSE_BUTTON_LEFT)
        );
    }

    /// Review finding: chord keys press modifiers first (stable), otherwise
    /// enigo attaches its accumulated modifier flags only to later presses
    /// and `s+ctrl` injects a bare `s` plus a lone ctrl.
    #[test]
    fn chord_keys_press_modifiers_first() {
        let ordered = ordered_chord_keys(&[Key::Char('s'), Key::Control]);
        assert_eq!(ordered, vec![Key::Control, Key::Char('s')]);
        let multi = ordered_chord_keys(&[Key::Char('h'), Key::Meta, Key::Char('u'), Key::Shift]);
        assert_eq!(
            multi,
            vec![Key::Meta, Key::Shift, Key::Char('h'), Key::Char('u')],
            "modifiers first, characters keep their relative order"
        );
        // Already-ordered input is unchanged (stable sort).
        let pre = ordered_chord_keys(&[Key::Shift, Key::Char('a')]);
        assert_eq!(pre, vec![Key::Shift, Key::Char('a')]);
    }
}
