[Service]
MemoryAccounting=yes
MemoryHigh=20%
MemoryMax=35%
MemorySwapMax=2G
OOMPolicy=kill
KillMode=control-group
TasksMax=128
ExecStopPost=-/usr/lib/pinvou3/supervisor/pinvou-supervisor snapshot-asr
