#!/usr/bin/env node
import assert from 'node:assert/strict';
import { after, test } from 'node:test';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { isValidVersion, main, updateCargoLockPackageVersion } from '../sync-version.mjs';

const TEST_FILE = fileURLToPath(import.meta.url);
const SYNC_SCRIPT = join(dirname(TEST_FILE), '..', 'sync-version.mjs');

function writeFixtureFile(root, relativePath, content) {
  const path = join(root, relativePath);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function createFixtureRepo() {
  const root = mkdtempSync(join(tmpdir(), 'pinvou-sync-version-'));
  writeFixtureFile(root, 'VERSION', '0.8.9\n');
  writeFixtureFile(root, 'pinvou3-app/src-tauri/tauri.conf.json', '{"version":"0.8.9"}\n');
  writeFixtureFile(root, 'pinvou3-app/src-tauri/Cargo.toml', '[package]\nname = "pinvou3-tauri"\nversion = "0.8.9"\n');
  writeFixtureFile(root, 'pinvou-knowledge/Cargo.toml', '[package]\nname = "pinvou-knowledge"\nversion = "0.8.9"\n');
  writeFixtureFile(root, 'pinvou-knowledge/Cargo.lock', '[[package]]\nname = "pinvou-knowledge"\nversion = "0.8.9"\n');
  writeFixtureFile(root, 'pinvou3-app/src-tauri/Cargo.lock', `[[package]]
name = "dependency"
version = "1.0.0"

[[package]]
name = "pinvou-knowledge"
version = "0.8.8"

[[package]]
name = "pinvou3-tauri"
version = "0.8.8"
`);
  writeFixtureFile(root, 'pinvou3-app/package.json', '{"version":"0.8.9"}\n');
  writeFixtureFile(root, 'scripts/.gitkeep', '');
  copyFileSync(SYNC_SCRIPT, join(root, 'scripts/sync-version.mjs'));
  return root;
}

function runFixtureScript(root, args = []) {
  return spawnSync(process.execPath, [join(root, 'scripts/sync-version.mjs'), ...args], {
    cwd: root,
    encoding: 'utf8',
  });
}

test('接受合法 SemVer 版本号', () => {
  for (const version of [
    '0.0.0',
    '0.6.5',
    '1.2.3-rc.1',
    '1.2.3-alpha.beta',
    '1.2.3+build.01',
    '1.2.3-rc.1+build.7',
  ]) {
    assert.equal(isValidVersion(version), true, version);
  }
});

test('拒绝会导致 Cargo 或打包阶段失败的非法版本号', () => {
  for (const version of [
    '1.2',
    'v1.2.3',
    '01.2.3',
    '1.02.3',
    '1.2.03',
    '1.2.3foo',
    '1.2.3-',
    '1.2.3-01',
    '1.2.3..',
    '1.2.3+',
  ]) {
    assert.equal(isValidVersion(version), false, version);
  }
});

test('只同步独立 Cargo.lock 中 pinvou-knowledge 自身的版本', () => {
  const lock = `# generated
[[package]]
name = "dependency"
version = "0.8.1"

[[package]]
name = "pinvou-knowledge"
version = "0.8.1"
dependencies = ["dependency"]
`;

  const result = updateCargoLockPackageVersion(lock, 'pinvou-knowledge', '0.8.3');

  assert.equal(result.version, '0.8.1');
  assert.match(result.content, /name = "dependency"\nversion = "0\.8\.1"/u);
  assert.match(result.content, /name = "pinvou-knowledge"\nversion = "0\.8\.3"/u);
});

test('Cargo.lock 缺少或重复根包时拒绝静默通过', () => {
  assert.throws(
    () => updateCargoLockPackageVersion('[[package]]\nname = "other"\nversion = "1.0.0"\n', 'pinvou-knowledge'),
    /实际找到 0 个/u,
  );
  const duplicate = `${'[[package]]\nname = "pinvou-knowledge"\nversion = "0.8.1"\n\n'.repeat(2)}`;
  assert.throws(
    () => updateCargoLockPackageVersion(duplicate, 'pinvou-knowledge'),
    /实际找到 2 个/u,
  );
});

// ---- main() 全量同步/校验：在临时目录沙箱中运行，不触碰真实仓库 ----

const TARGET_VERSION = '0.8.8';
const OLD_VERSION = '0.8.7';

// src-tauri/Cargo.lock 的真实形态：本 crate 与 path 依赖 pinvou-knowledge 各一个 [[package]] 段
function srcTauriLock(tauriVersion, knowledgeVersion) {
  return `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "pinvou-knowledge"
version = "${knowledgeVersion}"

[[package]]
name = "pinvou3-tauri"
version = "${tauriVersion}"
dependencies = [
 "pinvou-knowledge",
]
`;
}

function knowledgeLock(version) {
  return `# This file is automatically @generated by Cargo.
[[package]]
name = "serde"
version = "1.0.210"

[[package]]
name = "pinvou-knowledge"
version = "${version}"
dependencies = [
 "serde",
]
`;
}

const sandboxRoots = [];
after(() => {
  for (const root of sandboxRoots) {
    rmSync(root, { recursive: true, force: true });
  }
});

function createSandboxRoot() {
  const root = mkdtempSync(join(tmpdir(), 'pinvou-sync-version-'));
  sandboxRoots.push(root);
  mkdirSync(join(root, 'pinvou3-app/src-tauri'), { recursive: true });
  mkdirSync(join(root, 'pinvou-knowledge'), { recursive: true });
  // VERSION 是单一事实来源，已升到目标版本；其余文件停留在旧版本，等待同步
  writeFileSync(join(root, 'VERSION'), `${TARGET_VERSION}\n`);
  writeFileSync(join(root, 'pinvou3-app/src-tauri/tauri.conf.json'), `${JSON.stringify({ version: OLD_VERSION }, null, 2)}\n`);
  writeFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.toml'), `[package]\nname = "pinvou3-tauri"\nversion = "${OLD_VERSION}"\n`);
  writeFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.lock'), srcTauriLock(OLD_VERSION, OLD_VERSION));
  writeFileSync(join(root, 'pinvou-knowledge/Cargo.toml'), `[package]\nname = "pinvou-knowledge"\nversion = "${OLD_VERSION}"\n`);
  writeFileSync(join(root, 'pinvou-knowledge/Cargo.lock'), knowledgeLock(OLD_VERSION));
  writeFileSync(join(root, 'pinvou3-app/package.json'), `${JSON.stringify({ name: 'pinvou3-app', version: OLD_VERSION }, null, 2)}\n`);
  return root;
}

function readSandboxVersions(root) {
  const srcTauriLockContent = readFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.lock'), 'utf8');
  return {
    tauriConf: JSON.parse(readFileSync(join(root, 'pinvou3-app/src-tauri/tauri.conf.json'), 'utf8')).version,
    cargoToml: readFileSync(join(root, 'pinvou3-app/src-tauri/Cargo.toml'), 'utf8'),
    srcTauriTauri: updateCargoLockPackageVersion(srcTauriLockContent, 'pinvou3-tauri').version,
    srcTauriKnowledge: updateCargoLockPackageVersion(srcTauriLockContent, 'pinvou-knowledge').version,
    knowledgeLock: updateCargoLockPackageVersion(readFileSync(join(root, 'pinvou-knowledge/Cargo.lock'), 'utf8'), 'pinvou-knowledge').version,
    packageJson: JSON.parse(readFileSync(join(root, 'pinvou3-app/package.json'), 'utf8')).version,
  };
}

test('同步模式更新全部目标，含 src-tauri Cargo.lock 的两个包版本', () => {
  const root = createSandboxRoot();

  assert.equal(main(root), 0);

  const versions = readSandboxVersions(root);
  assert.equal(versions.tauriConf, TARGET_VERSION);
  assert.match(versions.cargoToml, /version = "0\.8\.8"/u);
  assert.equal(versions.srcTauriTauri, TARGET_VERSION);
  assert.equal(versions.srcTauriKnowledge, TARGET_VERSION);
  assert.equal(versions.knowledgeLock, TARGET_VERSION);
  assert.equal(versions.packageJson, TARGET_VERSION);
});

test('--check 全部一致时通过且保持只读', () => {
  const root = createSandboxRoot();
  assert.equal(main(root), 0);
  const before = readSandboxVersions(root);

  assert.equal(main(root, { checkOnly: true }), 0);

  const after = readSandboxVersions(root);
  assert.deepEqual(after, before);
  assert.equal(after.srcTauriTauri, TARGET_VERSION);
  assert.equal(after.srcTauriKnowledge, TARGET_VERSION);
});

test('--check 在 src-tauri Cargo.lock 落后一个版本时报错（真实回归场景）', () => {
  for (const packageName of ['pinvou3-tauri', 'pinvou-knowledge']) {
    const root = createSandboxRoot();
    assert.equal(main(root), 0);

    // 复现回归：src-tauri 的 Cargo.lock 漏改某一个包版本
    const lockPath = join(root, 'pinvou3-app/src-tauri/Cargo.lock');
    const result = updateCargoLockPackageVersion(readFileSync(lockPath, 'utf8'), packageName, OLD_VERSION);
    writeFileSync(lockPath, result.content);
    const before = readSandboxVersions(root);

    assert.equal(main(root, { checkOnly: true }), 1, packageName);
    // --check 只读：除手工构造的回退外，其余文件不得被改动
    const after = readSandboxVersions(root);
    assert.equal(after.srcTauriTauri, before.srcTauriTauri, packageName);
    assert.equal(after.srcTauriKnowledge, before.srcTauriKnowledge, packageName);
    assert.equal(after.knowledgeLock, TARGET_VERSION, packageName);
  }
});

test('src-tauri Cargo.lock 两个包各恰好一段，可分别更新且互不影响', () => {
  const lock = srcTauriLock(OLD_VERSION, OLD_VERSION);

  const tauriResult = updateCargoLockPackageVersion(lock, 'pinvou3-tauri', TARGET_VERSION);
  assert.equal(tauriResult.version, OLD_VERSION);
  assert.match(tauriResult.content, /name = "pinvou3-tauri"\nversion = "0\.8\.8"/u);
  assert.match(tauriResult.content, /name = "pinvou-knowledge"\nversion = "0\.8\.7"/u);

  const knowledgeResult = updateCargoLockPackageVersion(tauriResult.content, 'pinvou-knowledge', TARGET_VERSION);
  assert.equal(knowledgeResult.version, OLD_VERSION);
  assert.match(knowledgeResult.content, /name = "pinvou3-tauri"\nversion = "0\.8\.8"/u);
  assert.match(knowledgeResult.content, /name = "pinvou-knowledge"\nversion = "0\.8\.8"/u);
});

test('src-tauri Cargo.lock 中包缺失或重复时拒绝静默通过', () => {
  assert.throws(
    () => updateCargoLockPackageVersion('[[package]]\nname = "serde"\nversion = "1.0.0"\n', 'pinvou3-tauri'),
    /实际找到 0 个/u,
  );
  const duplicate = srcTauriLock(OLD_VERSION, OLD_VERSION) + '[[package]]\nname = "pinvou3-tauri"\nversion = "0.8.7"\n';
  assert.throws(
    () => updateCargoLockPackageVersion(duplicate, 'pinvou3-tauri'),
    /实际找到 2 个/u,
  );
});